"""Core data structures for the NAT hypothesis-driven research agent."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional


# ---------------------------------------------------------------------------
# Hypothesis — a testable claim about microstructure
# ---------------------------------------------------------------------------

@dataclass
class Hypothesis:
    """A testable claim generated by one of the five generators."""

    id: str                                       # HYP-{gen_prefix}-{counter}
    claim: str                                    # human-readable statement
    generator: str                                # systematic|spectral|regime|cross_asset|recycler
    priority: float                               # (ic_gain * novelty * data_ready) / runtime
    test_protocol: list[str]                      # nat commands in execution order
    thresholds: dict = field(default_factory=dict)  # go/no-go values per step
    status: str = "queued"                        # queued|running|passed|failed|replicated
    failure_reason: Optional[str] = None          # no_effect|no_replication|cost_killed|no_persistence|insufficient_data
    parent_id: Optional[str] = None               # recycled or derived hypothesis
    results: Optional[dict] = None                # raw output from nat commands
    created: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    completed: Optional[str] = None

    # Generator prefixes for ID generation
    GEN_PREFIX = {
        "systematic": "SYS",
        "spectral": "SPE",
        "regime": "REG",
        "cross_asset": "XAS",
        "recycler": "REC",
        "ensemble": "ENS",
    }

    @classmethod
    def register_prefix(cls, generator: str, prefix: str) -> None:
        """Register a new generator prefix for hypothesis ID generation."""
        cls.GEN_PREFIX[generator] = prefix

    @classmethod
    def create(
        cls,
        claim: str,
        generator: str,
        test_protocol: list[str],
        priority: float = 0.0,
        thresholds: Optional[dict] = None,
        parent_id: Optional[str] = None,
    ) -> Hypothesis:
        prefix = cls.GEN_PREFIX.get(generator, "UNK")
        short_id = uuid.uuid4().hex[:8]
        return cls(
            id=f"HYP-{prefix}-{short_id}",
            claim=claim,
            generator=generator,
            priority=priority,
            test_protocol=test_protocol,
            thresholds=thresholds or {},
            parent_id=parent_id,
        )

    def fail(self, reason: str) -> None:
        self.status = "failed"
        self.failure_reason = reason
        self.completed = datetime.now(timezone.utc).isoformat()

    def pass_discovery(self) -> None:
        self.status = "passed"

    def replicate(self) -> None:
        self.status = "replicated"
        self.completed = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> Hypothesis:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# RegisteredSignal — a validated, replicating alpha signal
# ---------------------------------------------------------------------------

@dataclass
class RegisteredSignal:
    """A signal that passed all three replication gates."""

    name: str                                     # e.g., "imbalance_l1_ent_gated"
    features: list[str]                           # input feature columns
    regime_gate: Optional[str] = None             # e.g., "ent_book_shape < P40"
    spectral_band: Optional[tuple] = None         # e.g., (0.005, 0.1) Hz
    extraction: str = "raw"                       # raw|kalman|bandpass
    horizon_s: float = 5.0                        # optimal forward horizon (seconds)
    expected_ic: float = 0.0                      # walk-forward OOS IC
    expected_ir: float = 0.0                      # IC information ratio
    decay_halflife_s: float = 0.0                 # signal decay from lag analysis
    symbols: list[str] = field(default_factory=lambda: ["BTC", "ETH", "SOL"])
    correlation_with: dict = field(default_factory=dict)  # pairwise corr
    status: str = "validated"                     # validated|paper|live|retired
    discovery_date: str = ""
    last_validated: str = ""
    hypothesis_id: str = ""                       # which hypothesis produced this

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> RegisteredSignal:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# GeneratorStats — per-generator performance tracking
# ---------------------------------------------------------------------------

@dataclass
class GeneratorStats:
    """Beta-prior multi-armed bandit for generator budget allocation."""

    attempts: int = 0
    successes: int = 0                            # passed all 3 gates

    @property
    def weight(self) -> float:
        """Thompson sampling weight: Beta(successes+1, failures+1)."""
        return (self.successes + 1) / (self.attempts + 2)

    @property
    def hit_rate(self) -> float:
        return self.successes / max(self.attempts, 1)

    def record(self, success: bool) -> None:
        self.attempts += 1
        if success:
            self.successes += 1
