#!/usr/bin/env bash
# Health snapshot for the NAT ingestor on su-35.
# Writes a markdown status file you can `cat` to see current state.
#
# Usage:
#   ./health_snapshot.sh                   # auto-detect most-recent log
#   ./health_snapshot.sh /path/to/log.txt  # specific log file
#
# Output: /home/onat/nat/logs/status_check_YYYY-MM-DD.md

set -uo pipefail

LOG_DIR=/home/onat/nat/logs
DATA_DIR=/home/onat/nat/data/features

if [[ $# -ge 1 ]]; then
    LOG="$1"
else
    LOG=$(ls -t "$LOG_DIR"/ingestor_*.log 2>/dev/null | head -1)
fi

OUT="$LOG_DIR/status_check_$(date +%Y-%m-%d).md"

# Strip ANSI from any log queries
plain() { sed 's/\x1b\[[0-9;]*m//g' "$LOG"; }

# Process state
PID=$(pgrep -f 'target/release/ing[^a-z]' | head -1)
if [[ -n "$PID" ]]; then
    ALIVE=yes
    ETIME=$(ps -o etime= -p "$PID" 2>/dev/null | tr -d ' ')
else
    ALIVE=no
    ETIME=n/a
fi

# Log-derived counts
WARN_COUNT=$(plain | grep -cE '\bWARN\b' || true)
ERROR_COUNT=$(plain | grep -cE '\bERROR\b' || true)
BOOK_STALE_COUNT=$(plain | grep -c 'BOOK STREAM STALE' || true)
PRICE_FROZEN_BOOK_STALE_COUNT=$(plain | grep 'MIDPRICE FROZEN' | grep -c 'regime="book_stale"' || true)
PRICE_FROZEN_BOOK_ALIVE_COUNT=$(plain | grep 'MIDPRICE FROZEN' | grep -c 'regime="book_alive"' || true)
RECONNECT_COUNT=$(plain | grep -c 'All subscriptions complete' || true)
HEALTH_TICKS=$(plain | grep -c 'Health summary' || true)

# Latest health summary per symbol
btc_h=$(plain | grep 'symbol=BTC' | grep 'Health summary' | tail -1 \
    | grep -oE 'book_age_s=Some\([0-9]+\)|price_change_age_s=Some\([0-9]+\)|last_midprice=Some\([0-9.]+\)|uptime="[^"]+"' | paste -sd ' ' -)
eth_h=$(plain | grep 'symbol=ETH' | grep 'Health summary' | tail -1 \
    | grep -oE 'book_age_s=Some\([0-9]+\)|price_change_age_s=Some\([0-9]+\)|last_midprice=Some\([0-9.]+\)|uptime="[^"]+"' | paste -sd ' ' -)
sol_h=$(plain | grep 'symbol=SOL' | grep 'Health summary' | tail -1 \
    | grep -oE 'book_age_s=Some\([0-9]+\)|price_change_age_s=Some\([0-9]+\)|last_midprice=Some\([0-9.]+\)|uptime="[^"]+"' | paste -sd ' ' -)

# Data growth — total bytes today and yesterday
today=$(date -u +%Y-%m-%d)
yesterday=$(date -u -d yesterday +%Y-%m-%d)
bytes_today=$(du -sb "$DATA_DIR/$today" 2>/dev/null | awk '{print $1}')
bytes_yesterday=$(du -sb "$DATA_DIR/$yesterday" 2>/dev/null | awk '{print $1}')
files_today=$(ls "$DATA_DIR/$today/" 2>/dev/null | wc -l)
files_yesterday=$(ls "$DATA_DIR/$yesterday/" 2>/dev/null | wc -l)

# Recent freeze events (last 10)
recent_freezes=$(plain | grep -E 'BOOK STREAM STALE|MIDPRICE FROZEN.*book_stale|Connection stale' | tail -10 || true)

# systemd-inhibit lock still active? Match the WHO column == "ing" exactly
# (naive 'ing\s' regex matches 'polling ' in UPower's WHY column).
INHIBIT=$(systemd-inhibit --list 2>/dev/null | awk '$1=="ing"' | head -1)
INHIBIT="${INHIBIT:-none}"

# Last log line timestamp (for liveness)
last_line=$(plain | tail -1 | grep -oE '2026-[0-9-]+T[0-9:.]+Z' | head -1 || echo 'unknown')

cat > "$OUT" <<EOF
# Ingestor Status — $(date '+%Y-%m-%d %H:%M %Z')

**Log file:** \`$LOG\`

## Process

- PID alive: **$ALIVE** ${PID:+(PID $PID)}
- Uptime: $ETIME
- Last log line timestamp: \`$last_line\`
- systemd-inhibit lock: \`$INHIBIT\`

## Counters (cumulative for this log)

| metric | count |
|---|---:|
| Health summary lines emitted | $HEALTH_TICKS |
| WARN lines | $WARN_COUNT |
| ERROR lines | $ERROR_COUNT |
| BOOK STREAM STALE events | $BOOK_STALE_COUNT |
| MIDPRICE FROZEN regime=book_stale | $PRICE_FROZEN_BOOK_STALE_COUNT |
| MIDPRICE FROZEN regime=book_alive | $PRICE_FROZEN_BOOK_ALIVE_COUNT |
| Reconnect events | $RECONNECT_COUNT |

## Latest health summary per symbol

- **BTC:** $btc_h
- **ETH:** $eth_h
- **SOL:** $sol_h

## Data growth

- Today ($today): $files_today files, $bytes_today bytes
- Yesterday ($yesterday): $files_yesterday files, $bytes_yesterday bytes

## Recent failure-class events (last 10 lines)

\`\`\`
$recent_freezes
\`\`\`

## Verdict heuristic

- alive=yes + ERROR=0 + book_stale<5 + reconnect<50 + uptime > 12h → **HEALTHY**
- alive=no → **STOPPED** (process died)
- ERROR>0 OR book_stale>=5 → **NEEDS ATTENTION**

Generated by health_snapshot.sh
EOF

echo "$OUT"
