#!/usr/bin/env python3
"""
Data Validation Script for ING Feature Data

Validates Parquet files generated by the ingestor:
- Continuity: No gaps larger than threshold
- Distributions: Features within expected ranges
- NaN ratio: Less than threshold after warmup
- File integrity: All files readable
- Cross-symbol consistency: Similar row counts across symbols

Usage:
    python scripts/validate_data.py [DATA_DIR] [--verbose] [--hours N]

Examples:
    python scripts/validate_data.py                    # Validate default directory
    python scripts/validate_data.py ./data/features   # Validate specific directory
    python scripts/validate_data.py --hours 24        # Only last 24 hours
    python scripts/validate_data.py --verbose         # Show detailed output
"""

import argparse
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import numpy as np
import pyarrow.parquet as pq
import pandas as pd


# =============================================================================
# Configuration
# =============================================================================

@dataclass
class ValidationConfig:
    """Validation thresholds and settings."""
    # Continuity
    max_gap_seconds: float = 5.0          # Max allowed gap between records
    min_records_per_hour: int = 30000     # Expected ~36000 at 100ms (10/sec * 3600)

    # NaN handling
    max_nan_ratio: float = 0.01           # Max 1% NaN after warmup
    warmup_seconds: int = 60              # Ignore first 60s for NaN check

    # Feature ranges (will flag if outside)
    feature_ranges: dict = field(default_factory=lambda: {
        'midprice': (0.001, 1_000_000),       # Price must be positive
        'spread_bps': (0, 1000),               # Spread 0-10%
        'qty_l1': (-1, 1),                     # Imbalance -1 to 1
        'returns_1m': (-1, 1),                 # Vol reasonable
        'vpin_10': (0, 1),                     # VPIN 0-1
        'kyle_lambda_100': (-1e6, 1e6),        # Lambda can vary
    })

    # Cross-symbol
    max_count_ratio_diff: float = 0.1     # Max 10% difference in row counts


# =============================================================================
# Validation Results
# =============================================================================

@dataclass
class CheckResult:
    """Result of a single validation check."""
    name: str
    passed: bool
    message: str
    details: Optional[dict] = None


@dataclass
class ValidationReport:
    """Full validation report."""
    data_dir: str
    timestamp: datetime
    total_files: int
    total_rows: int
    symbols: list
    date_range: tuple
    checks: list

    @property
    def passed(self) -> bool:
        return all(c.passed for c in self.checks)

    def print_report(self, verbose: bool = False):
        """Print formatted report."""
        print("\n" + "=" * 70)
        print("               ING DATA VALIDATION REPORT")
        print("=" * 70)
        print(f"  Data Directory: {self.data_dir}")
        print(f"  Report Time:    {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  Files Scanned:  {self.total_files}")
        print(f"  Total Rows:     {self.total_rows:,}")
        print(f"  Symbols:        {', '.join(self.symbols)}")
        if self.date_range[0] and self.date_range[1]:
            print(f"  Date Range:     {self.date_range[0]} to {self.date_range[1]}")
        print("=" * 70)
        print("\n  CHECK RESULTS:\n")

        for check in self.checks:
            status = "\033[92mPASS\033[0m" if check.passed else "\033[91mFAIL\033[0m"
            print(f"  [{status}] {check.name}")
            print(f"         {check.message}")
            if verbose and check.details:
                for k, v in check.details.items():
                    print(f"         - {k}: {v}")
            print()

        print("=" * 70)
        if self.passed:
            print("  \033[92mOVERALL: ALL CHECKS PASSED\033[0m")
        else:
            failed = [c.name for c in self.checks if not c.passed]
            print(f"  \033[91mOVERALL: {len(failed)} CHECK(S) FAILED\033[0m")
            print(f"  Failed: {', '.join(failed)}")
        print("=" * 70 + "\n")


# =============================================================================
# Data Loading
# =============================================================================

def find_parquet_files(data_dir: Path, hours: Optional[int] = None) -> list:
    """Find all Parquet files, optionally filtered by age."""
    files = list(data_dir.rglob("*.parquet"))

    if hours:
        cutoff = datetime.now() - timedelta(hours=hours)
        filtered = []
        for f in files:
            # Try to extract date from path (YYYY-MM-DD/file.parquet)
            try:
                date_str = f.parent.name
                file_date = datetime.strptime(date_str, "%Y-%m-%d")
                if file_date >= cutoff.replace(hour=0, minute=0, second=0):
                    filtered.append(f)
            except ValueError:
                # Can't parse date, include anyway
                filtered.append(f)
        files = filtered

    return sorted(files)


def load_data(files: list) -> pd.DataFrame:
    """Load and concatenate Parquet files."""
    if not files:
        return pd.DataFrame()

    dfs = []
    for f in files:
        try:
            df = pq.read_table(f).to_pandas()
            dfs.append(df)
        except Exception as e:
            print(f"  Warning: Could not read {f}: {e}")

    if not dfs:
        return pd.DataFrame()

    return pd.concat(dfs, ignore_index=True)


# =============================================================================
# Validation Checks
# =============================================================================

def check_file_integrity(files: list) -> CheckResult:
    """Check that all Parquet files are readable."""
    errors = []
    for f in files:
        try:
            pq.read_table(f)
        except Exception as e:
            errors.append(f"{f.name}: {e}")

    if errors:
        return CheckResult(
            name="File Integrity",
            passed=False,
            message=f"{len(errors)} file(s) failed to read",
            details={"errors": errors[:5]}  # Show first 5
        )

    return CheckResult(
        name="File Integrity",
        passed=True,
        message=f"All {len(files)} files readable"
    )


def get_timestamp_col(df: pd.DataFrame) -> str:
    """Get the timestamp column name (handles schema variations)."""
    if 'timestamp_ns' in df.columns:
        return 'timestamp_ns'
    elif 'timestamp' in df.columns:
        return 'timestamp'
    else:
        raise ValueError("No timestamp column found")


def check_continuity(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check for gaps in timestamps."""
    if df.empty:
        return CheckResult(
            name="Continuity",
            passed=False,
            message="No data to check"
        )

    ts_col = get_timestamp_col(df)

    # Sort by timestamp
    df_sorted = df.sort_values(ts_col)

    # Calculate gaps per symbol
    gap_info = {}
    max_gap = 0
    total_gaps = 0

    for symbol in df['symbol'].unique():
        sym_df = df_sorted[df_sorted['symbol'] == symbol]
        timestamps = sym_df[ts_col].values

        if len(timestamps) < 2:
            continue

        # Calculate gaps in seconds
        gaps = np.diff(timestamps) / 1e9
        large_gaps = gaps[gaps > config.max_gap_seconds]

        if len(large_gaps) > 0:
            gap_info[symbol] = {
                'count': len(large_gaps),
                'max_gap': float(np.max(large_gaps)),
                'avg_gap': float(np.mean(large_gaps))
            }
            max_gap = max(max_gap, np.max(large_gaps))
            total_gaps += len(large_gaps)

    if total_gaps > 0:
        return CheckResult(
            name="Continuity",
            passed=False,
            message=f"{total_gaps} gaps > {config.max_gap_seconds}s detected (max: {max_gap:.1f}s)",
            details=gap_info
        )

    return CheckResult(
        name="Continuity",
        passed=True,
        message=f"No gaps > {config.max_gap_seconds}s detected"
    )


def check_nan_ratio(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check NaN ratio in feature columns."""
    if df.empty:
        return CheckResult(
            name="NaN Ratio",
            passed=False,
            message="No data to check"
        )

    # Skip metadata columns
    meta_cols = ['timestamp_ns', 'timestamp', 'symbol', 'sequence_id']
    feature_cols = [c for c in df.columns if c not in meta_cols]

    # Filter out warmup period
    try:
        ts_col = get_timestamp_col(df)
        min_ts = df[ts_col].min()
        warmup_cutoff = min_ts + (config.warmup_seconds * 1e9)
        df_post_warmup = df[df[ts_col] >= warmup_cutoff]
    except (ValueError, KeyError):
        df_post_warmup = df

    if df_post_warmup.empty:
        return CheckResult(
            name="NaN Ratio",
            passed=True,
            message="Insufficient data after warmup filter"
        )

    # Calculate NaN ratio per column
    nan_ratios = {}
    high_nan_cols = []

    for col in feature_cols:
        if col in df_post_warmup.columns:
            ratio = df_post_warmup[col].isna().mean()
            if ratio > config.max_nan_ratio:
                nan_ratios[col] = f"{ratio:.2%}"
                high_nan_cols.append(col)

    overall_nan = df_post_warmup[feature_cols].isna().mean().mean()

    if high_nan_cols:
        return CheckResult(
            name="NaN Ratio",
            passed=False,
            message=f"{len(high_nan_cols)} columns exceed {config.max_nan_ratio:.0%} NaN threshold",
            details={"columns": nan_ratios}
        )

    return CheckResult(
        name="NaN Ratio",
        passed=True,
        message=f"Overall NaN ratio: {overall_nan:.2%} (threshold: {config.max_nan_ratio:.0%})"
    )


def check_feature_ranges(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that key features are within expected ranges."""
    if df.empty:
        return CheckResult(
            name="Feature Ranges",
            passed=False,
            message="No data to check"
        )

    out_of_range = {}

    for feature, (min_val, max_val) in config.feature_ranges.items():
        if feature not in df.columns:
            continue

        values = df[feature].dropna()
        if len(values) == 0:
            continue

        below = (values < min_val).sum()
        above = (values > max_val).sum()

        if below > 0 or above > 0:
            out_of_range[feature] = {
                'below_min': int(below),
                'above_max': int(above),
                'actual_range': f"[{values.min():.4g}, {values.max():.4g}]",
                'expected': f"[{min_val}, {max_val}]"
            }

    if out_of_range:
        return CheckResult(
            name="Feature Ranges",
            passed=False,
            message=f"{len(out_of_range)} features outside expected range",
            details=out_of_range
        )

    return CheckResult(
        name="Feature Ranges",
        passed=True,
        message=f"All {len(config.feature_ranges)} monitored features within range"
    )


def check_cross_symbol_consistency(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that all symbols have similar row counts."""
    if df.empty:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=False,
            message="No data to check"
        )

    counts = df.groupby('symbol').size()

    if len(counts) < 2:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=True,
            message=f"Only {len(counts)} symbol(s), skipping comparison"
        )

    max_count = counts.max()
    min_count = counts.min()
    ratio_diff = (max_count - min_count) / max_count

    details = {sym: int(cnt) for sym, cnt in counts.items()}
    details['ratio_diff'] = f"{ratio_diff:.1%}"

    if ratio_diff > config.max_count_ratio_diff:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=False,
            message=f"Row count varies by {ratio_diff:.1%} (threshold: {config.max_count_ratio_diff:.0%})",
            details=details
        )

    return CheckResult(
        name="Cross-Symbol Consistency",
        passed=True,
        message=f"Row counts consistent across symbols (diff: {ratio_diff:.1%})",
        details=details
    )


def check_data_rate(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that data rate meets expectations."""
    if df.empty:
        return CheckResult(
            name="Data Rate",
            passed=False,
            message="No data to check"
        )

    ts_col = get_timestamp_col(df)

    # Calculate time span
    min_ts = df[ts_col].min()
    max_ts = df[ts_col].max()
    duration_hours = (max_ts - min_ts) / 1e9 / 3600

    if duration_hours < 0.1:
        return CheckResult(
            name="Data Rate",
            passed=True,
            message=f"Insufficient duration ({duration_hours:.2f}h) for rate check"
        )

    # Check rate per symbol
    rate_info = {}
    low_rate_symbols = []

    for symbol in df['symbol'].unique():
        sym_count = len(df[df['symbol'] == symbol])
        rate_per_hour = sym_count / duration_hours
        rate_info[symbol] = f"{rate_per_hour:.0f}/hour"

        if rate_per_hour < config.min_records_per_hour:
            low_rate_symbols.append(symbol)

    rate_info['duration_hours'] = f"{duration_hours:.2f}"

    if low_rate_symbols:
        return CheckResult(
            name="Data Rate",
            passed=False,
            message=f"{len(low_rate_symbols)} symbol(s) below {config.min_records_per_hour}/hour",
            details=rate_info
        )

    return CheckResult(
        name="Data Rate",
        passed=True,
        message=f"All symbols meet minimum rate ({config.min_records_per_hour}/hour)",
        details=rate_info
    )


def check_sequence_monotonicity(df: pd.DataFrame) -> CheckResult:
    """Check that sequence IDs are monotonically increasing per symbol."""
    if df.empty:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=False,
            message="No data to check"
        )

    # Check if sequence_id column exists
    if 'sequence_id' not in df.columns:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=True,
            message="No sequence_id column (older schema), skipping"
        )

    issues = {}

    for symbol in df['symbol'].unique():
        ts_col = get_timestamp_col(df)
        sym_df = df[df['symbol'] == symbol].sort_values(ts_col)
        seq_ids = sym_df['sequence_id'].values

        if len(seq_ids) < 2:
            continue

        # Check for non-increasing sequences
        diffs = np.diff(seq_ids)
        non_increasing = (diffs <= 0).sum()

        if non_increasing > 0:
            issues[symbol] = {
                'non_increasing_count': int(non_increasing),
                'first_seq': int(seq_ids[0]),
                'last_seq': int(seq_ids[-1])
            }

    if issues:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=False,
            message=f"{len(issues)} symbol(s) have non-monotonic sequences",
            details=issues
        )

    return CheckResult(
        name="Sequence Monotonicity",
        passed=True,
        message="All sequences monotonically increasing"
    )


# =============================================================================
# Main Validation
# =============================================================================

def validate(data_dir: Path, config: ValidationConfig, hours: Optional[int] = None) -> ValidationReport:
    """Run all validation checks."""
    print(f"\n  Scanning {data_dir}...")

    # Find files
    files = find_parquet_files(data_dir, hours)
    print(f"  Found {len(files)} Parquet file(s)")

    if not files:
        return ValidationReport(
            data_dir=str(data_dir),
            timestamp=datetime.now(),
            total_files=0,
            total_rows=0,
            symbols=[],
            date_range=(None, None),
            checks=[CheckResult(
                name="Data Presence",
                passed=False,
                message="No Parquet files found"
            )]
        )

    # Load data
    print("  Loading data...")
    df = load_data(files)
    print(f"  Loaded {len(df):,} rows")

    # Extract metadata
    symbols = sorted(df['symbol'].unique().tolist()) if not df.empty else []

    if not df.empty:
        try:
            ts_col = get_timestamp_col(df)
            min_ts = pd.Timestamp(df[ts_col].min(), unit='ns')
            max_ts = pd.Timestamp(df[ts_col].max(), unit='ns')
            date_range = (min_ts.strftime('%Y-%m-%d %H:%M'), max_ts.strftime('%Y-%m-%d %H:%M'))
        except (ValueError, KeyError):
            date_range = (None, None)
    else:
        date_range = (None, None)

    # Run checks
    print("  Running validation checks...")
    checks = [
        check_file_integrity(files),
        check_continuity(df, config),
        check_nan_ratio(df, config),
        check_feature_ranges(df, config),
        check_cross_symbol_consistency(df, config),
        check_data_rate(df, config),
        check_sequence_monotonicity(df),
    ]

    return ValidationReport(
        data_dir=str(data_dir),
        timestamp=datetime.now(),
        total_files=len(files),
        total_rows=len(df),
        symbols=symbols,
        date_range=date_range,
        checks=checks
    )


def main():
    parser = argparse.ArgumentParser(
        description="Validate ING feature data quality",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "data_dir",
        nargs="?",
        default="./data/features",
        help="Data directory to validate (default: ./data/features)"
    )
    parser.add_argument(
        "--hours",
        type=int,
        help="Only validate data from last N hours"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed output"
    )
    parser.add_argument(
        "--max-gap",
        type=float,
        default=5.0,
        help="Max allowed gap in seconds (default: 5.0)"
    )
    parser.add_argument(
        "--max-nan",
        type=float,
        default=0.01,
        help="Max allowed NaN ratio (default: 0.01)"
    )

    args = parser.parse_args()

    # Setup config
    config = ValidationConfig(
        max_gap_seconds=args.max_gap,
        max_nan_ratio=args.max_nan
    )

    # Run validation
    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"\n  Error: Directory does not exist: {data_dir}")
        sys.exit(1)

    report = validate(data_dir, config, args.hours)
    report.print_report(verbose=args.verbose)

    # Exit with appropriate code
    sys.exit(0 if report.passed else 1)


if __name__ == "__main__":
    main()
