#!/usr/bin/env python3
"""
Data Validation Script for ING Feature Data

Validates Parquet files generated by the ingestor:
- Continuity: No gaps larger than threshold
- Distributions: Features within expected ranges
- NaN ratio: Less than threshold after warmup
- File integrity: All files readable
- Cross-symbol consistency: Similar row counts across symbols

Usage:
    python scripts/validate_data.py [DATA_DIR] [--verbose] [--hours N]

Examples:
    python scripts/validate_data.py                    # Validate default directory
    python scripts/validate_data.py ./data/features   # Validate specific directory
    python scripts/validate_data.py --hours 24        # Only last 24 hours
    python scripts/validate_data.py --verbose         # Show detailed output
"""

import argparse
import json as _json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import numpy as np
import pyarrow.parquet as pq
import pandas as pd


# =============================================================================
# Configuration
# =============================================================================

@dataclass
class ValidationConfig:
    """Validation thresholds and settings."""
    # Continuity
    max_gap_seconds: float = 5.0          # Max allowed gap between records
    min_records_per_hour: int = 30000     # Expected ~36000 at 100ms (10/sec * 3600)

    # NaN handling
    max_nan_ratio: float = 0.01           # Max 1% NaN after warmup
    warmup_seconds: int = 60              # Ignore first 60s for NaN check

    # Feature ranges (will flag if outside)
    feature_ranges: dict = field(default_factory=lambda: {
        'midprice': (0.001, 1_000_000),       # Price must be positive
        'spread_bps': (0, 1000),               # Spread 0-10%
        'qty_l1': (-1, 1),                     # Imbalance -1 to 1
        'returns_1m': (-1, 1),                 # Vol reasonable
        'vpin_10': (0, 1),                     # VPIN 0-1
        'kyle_lambda_100': (-1e6, 1e6),        # Lambda can vary
    })

    # Cross-symbol
    max_count_ratio_diff: float = 0.1     # Max 10% difference in row counts

    # Category liveness (BUG-6). A category whose every column is 100% NaN means a
    # subsystem stopped computing — categorically different from scattered NaN, which
    # is `NaN Ratio`'s job.
    #
    # The declared-dead set is DECLARED, never inferred from a threshold, and it is
    # short on purpose. Only `hm` (heatmap, 8 features) qualifies: a per-category
    # census over all 76 day-directories found 0/53 days with a single finite value.
    #
    # A raw alive/total ratio is NOT the right instrument here and must not be used as
    # one. `whale` 36/76 and `concentration` 36/76 look half-dead by that count, but the
    # count is dominated by April-to-mid-June, before the position tracker was deployed
    # at all. Split at the 06-18 deploy and they are healthy:
    #
    #     since 2026-06-18       alive / dead      dead days
    #     whale                    35 / 3          06-19, 08-04, 08-09
    #     concentration            35 / 3          06-19, 08-04, 08-09
    #     liquidation              34 / 4          06-19, 07-27, 08-04, 08-09
    #     regime                   23 / 15         contiguous DEAD since 07-26
    #
    # So there is exactly one standing regression (`regime`), not four. The scattered
    # dead days for the position-tracker trio are all low-coverage days — the same days
    # on which no continuous run reaches these categories' readiness windows — which is
    # a symptom of ingestion continuity, not of those categories being broken.
    #
    # Adding a prefix here says "this subsystem is known to be off forever", which
    # should cost an edit and a justification rather than happen silently.
    expected_dead_categories: frozenset = frozenset({"hm"})


# =============================================================================
# Validation Results
# =============================================================================

# Checks whose failure is a hard FAIL (data is unusable). Any other failing
# check is a soft WARN. Used to derive the three-level verdict (PASS/WARN/FAIL).
HARD_CHECKS = frozenset({
    "Data Presence",
    "File Integrity",
    "Continuity",
    "NaN Ratio",
    "Category Liveness",
    "Sequence Monotonicity",
})


@dataclass
class CheckResult:
    """Result of a single validation check."""
    name: str
    passed: bool
    message: str
    details: Optional[dict] = None


@dataclass
class ValidationReport:
    """Full validation report."""
    data_dir: str
    timestamp: datetime
    total_files: int
    total_rows: int
    symbols: list
    date_range: tuple
    checks: list

    @property
    def passed(self) -> bool:
        return all(c.passed for c in self.checks)

    @property
    def verdict(self) -> str:
        """Three-level verdict: FAIL if any hard check fails, else WARN if any
        soft check fails, else PASS."""
        if any(not c.passed and c.name in HARD_CHECKS for c in self.checks):
            return "FAIL"
        if any(not c.passed for c in self.checks):
            return "WARN"
        return "PASS"

    def to_dict(self) -> dict:
        """Machine-readable report (JSON-serializable)."""
        return {
            "data_dir": self.data_dir,
            "timestamp": self.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "verdict": self.verdict,
            "passed": self.passed,
            "total_files": self.total_files,
            "total_rows": self.total_rows,
            "symbols": self.symbols,
            "date_range": list(self.date_range),
            "checks": [
                {
                    "name": c.name,
                    "passed": c.passed,
                    "hard": c.name in HARD_CHECKS,
                    "message": c.message,
                    "details": c.details,
                }
                for c in self.checks
            ],
        }

    def print_report(self, verbose: bool = False):
        """Print formatted report."""
        print("\n" + "=" * 70)
        print("               ING DATA VALIDATION REPORT")
        print("=" * 70)
        print(f"  Data Directory: {self.data_dir}")
        print(f"  Report Time:    {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  Files Scanned:  {self.total_files}")
        print(f"  Total Rows:     {self.total_rows:,}")
        print(f"  Symbols:        {', '.join(self.symbols)}")
        if self.date_range[0] and self.date_range[1]:
            print(f"  Date Range:     {self.date_range[0]} to {self.date_range[1]}")
        print("=" * 70)
        print("\n  CHECK RESULTS:\n")

        for check in self.checks:
            status = "\033[92mPASS\033[0m" if check.passed else "\033[91mFAIL\033[0m"
            print(f"  [{status}] {check.name}")
            print(f"         {check.message}")
            if verbose and check.details:
                for k, v in check.details.items():
                    print(f"         - {k}: {v}")
            print()

        print("=" * 70)
        verdict = self.verdict
        if verdict == "PASS":
            print("  \033[92mOVERALL: PASS — all checks passed\033[0m")
        elif verdict == "WARN":
            warned = [c.name for c in self.checks if not c.passed]
            print(f"  \033[93mOVERALL: WARN — {len(warned)} soft check(s) flagged\033[0m")
            print(f"  Warnings: {', '.join(warned)}")
        else:
            failed = [c.name for c in self.checks if not c.passed]
            hard = [c.name for c in self.checks if not c.passed and c.name in HARD_CHECKS]
            print(f"  \033[91mOVERALL: FAIL — {len(failed)} check(s) failed\033[0m")
            print(f"  Failed: {', '.join(failed)}  (hard: {', '.join(hard)})")
        print("=" * 70 + "\n")


# =============================================================================
# Data Loading
# =============================================================================

def find_parquet_files(data_dir: Path, hours: Optional[int] = None) -> list:
    """Find Parquet files, optionally filtered by age.

    If ``data_dir`` points at a single ``.parquet`` file, that file is returned
    verbatim (the ``--hours`` age filter does not apply to an explicitly named
    file). Otherwise the directory is scanned recursively.
    """
    if data_dir.is_file():
        return [data_dir]

    files = list(data_dir.rglob("*.parquet"))

    if hours:
        cutoff = datetime.now() - timedelta(hours=hours)
        filtered = []
        for f in files:
            # Try to extract date from path (YYYY-MM-DD/file.parquet)
            try:
                date_str = f.parent.name
                file_date = datetime.strptime(date_str, "%Y-%m-%d")
                if file_date >= cutoff.replace(hour=0, minute=0, second=0):
                    filtered.append(f)
            except ValueError:
                # Can't parse date, include anyway
                filtered.append(f)
        files = filtered

    return sorted(files)


def load_data(files: list) -> pd.DataFrame:
    """Load and concatenate Parquet files."""
    if not files:
        return pd.DataFrame()

    dfs = []
    for f in files:
        try:
            df = pq.read_table(f).to_pandas()
            dfs.append(df)
        except Exception as e:
            print(f"  Warning: Could not read {f}: {e}")

    if not dfs:
        return pd.DataFrame()

    return pd.concat(dfs, ignore_index=True)


# =============================================================================
# Validation Checks
# =============================================================================

def check_file_integrity(files: list) -> CheckResult:
    """Check that all Parquet files are readable."""
    errors = []
    for f in files:
        try:
            pq.read_table(f)
        except Exception as e:
            errors.append(f"{f.name}: {e}")

    if errors:
        return CheckResult(
            name="File Integrity",
            passed=False,
            message=f"{len(errors)} file(s) failed to read",
            details={"errors": errors[:5]}  # Show first 5
        )

    return CheckResult(
        name="File Integrity",
        passed=True,
        message=f"All {len(files)} files readable"
    )


def get_timestamp_col(df: pd.DataFrame) -> str:
    """Get the timestamp column name (handles schema variations)."""
    if 'timestamp_ns' in df.columns:
        return 'timestamp_ns'
    elif 'timestamp' in df.columns:
        return 'timestamp'
    else:
        raise ValueError("No timestamp column found")


def check_continuity(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check for gaps in timestamps."""
    if df.empty:
        return CheckResult(
            name="Continuity",
            passed=False,
            message="No data to check"
        )

    ts_col = get_timestamp_col(df)

    # Sort by timestamp
    df_sorted = df.sort_values(ts_col)

    # Calculate gaps per symbol
    gap_info = {}
    max_gap = 0
    total_gaps = 0

    for symbol in df['symbol'].unique():
        sym_df = df_sorted[df_sorted['symbol'] == symbol]
        timestamps = sym_df[ts_col].values

        if len(timestamps) < 2:
            continue

        # Calculate gaps in seconds
        gaps = np.diff(timestamps) / 1e9
        large_gaps = gaps[gaps > config.max_gap_seconds]

        if len(large_gaps) > 0:
            gap_info[symbol] = {
                'count': len(large_gaps),
                'max_gap': float(np.max(large_gaps)),
                'avg_gap': float(np.mean(large_gaps))
            }
            max_gap = max(max_gap, np.max(large_gaps))
            total_gaps += len(large_gaps)

    if total_gaps > 0:
        return CheckResult(
            name="Continuity",
            passed=False,
            message=f"{total_gaps} gaps > {config.max_gap_seconds}s detected (max: {max_gap:.1f}s)",
            details=gap_info
        )

    return CheckResult(
        name="Continuity",
        passed=True,
        message=f"No gaps > {config.max_gap_seconds}s detected"
    )


def check_nan_ratio(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check NaN ratio in feature columns."""
    if df.empty:
        return CheckResult(
            name="NaN Ratio",
            passed=False,
            message="No data to check"
        )

    # Skip metadata columns
    meta_cols = ['timestamp_ns', 'timestamp', 'symbol', 'sequence_id']
    feature_cols = [c for c in df.columns if c not in meta_cols]

    # Filter out warmup period
    try:
        ts_col = get_timestamp_col(df)
        min_ts = df[ts_col].min()
        warmup_cutoff = min_ts + (config.warmup_seconds * 1e9)
        df_post_warmup = df[df[ts_col] >= warmup_cutoff]
    except (ValueError, KeyError):
        df_post_warmup = df

    if df_post_warmup.empty:
        return CheckResult(
            name="NaN Ratio",
            passed=True,
            message="Insufficient data after warmup filter"
        )

    # Calculate NaN ratio per column
    nan_ratios = {}
    high_nan_cols = []

    for col in feature_cols:
        if col in df_post_warmup.columns:
            ratio = df_post_warmup[col].isna().mean()
            if ratio > config.max_nan_ratio:
                nan_ratios[col] = f"{ratio:.2%}"
                high_nan_cols.append(col)

    overall_nan = df_post_warmup[feature_cols].isna().mean().mean()

    if high_nan_cols:
        return CheckResult(
            name="NaN Ratio",
            passed=False,
            message=f"{len(high_nan_cols)} columns exceed {config.max_nan_ratio:.0%} NaN threshold",
            details={"columns": nan_ratios}
        )

    return CheckResult(
        name="NaN Ratio",
        passed=True,
        message=f"Overall NaN ratio: {overall_nan:.2%} (threshold: {config.max_nan_ratio:.0%})"
    )


#: Columns that are not features and must never be scored as a category.
_META_COLS = ('timestamp_ns', 'timestamp', 'symbol', 'sequence_id')


#: Prefixes that belong to one manifest category but do not share a common stem.
#: Concentration is the only such case: its 15 columns are named after the statistic
#: (`gini`, `theil`, `herfindahl`, `top5`, …) rather than carrying a `conc_` prefix, so
#: splitting on the first `_` shatters one category into fourteen singletons and every
#: one of them reads as "a dead category". Found by real-parquet smoke, which is the
#: only place it could have been found — the planted frames use tidy prefixes.
_CONCENTRATION_PREFIXES = frozenset({
    'concentration', 'active', 'positions', 'position', 'largest', 'nearest',
    'top5', 'top10', 'top20', 'top50', 'herfindahl', 'gini', 'theil', 'hhi',
})


def _category_of(column: str) -> str:
    """The feature category a column belongs to, per `FEATURES.md`'s 21 categories.

    Mostly the prefix up to the first `_` (`raw_`, `imbalance_`, `regime_`, `hm_`, …),
    with concentration's statistic-named columns folded back into one category.
    """
    stem = column.split('_', 1)[0]
    return 'concentration' if stem in _CONCENTRATION_PREFIXES else stem


def check_category_liveness(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Flag whole feature CATEGORIES that are 100% NaN (BUG-6).

    `NaN Ratio` already reports dead columns, but it reports them one per line: on
    2026-08-08 it said "90 columns exceed 1% NaN threshold" — the same sentence it
    printed on 2026-07-15, when the `regime_` category was still alive. A message that
    does not change when a 23-feature subsystem dies cannot raise the alarm, and BUG-6
    went unnoticed for 13 days behind exactly that sentence.

    So this check works at the category level, where the signal survives: 90 flagged
    columns collapse to one named item. A category is dead only when *every* one of its
    columns is wholly NaN — partial deadness is noise and belongs to `NaN Ratio`.

    There is deliberately no warmup grace. A category NaN for an entire file never
    started; warmup shows up as a leading NaN block, not a column of them.
    """
    if df.empty:
        return CheckResult(
            name="Category Liveness",
            passed=False,
            message="No data to check",
        )

    feature_cols = [c for c in df.columns if c not in _META_COLS]
    categories: dict[str, dict[str, int]] = {}
    for col in feature_cols:
        cat = _category_of(col)
        entry = categories.setdefault(cat, {"dead": 0, "total": 0})
        entry["total"] += 1
        series = pd.to_numeric(df[col], errors="coerce")
        if not np.isfinite(series.to_numpy(dtype=float)).any():
            entry["dead"] += 1

    wholly_dead = sorted(
        cat for cat, e in categories.items()
        if e["total"] > 0 and e["dead"] == e["total"]
    )
    undeclared = [c for c in wholly_dead if c not in config.expected_dead_categories]
    declared = [c for c in wholly_dead if c in config.expected_dead_categories]

    details = {
        "categories": categories,
        "dead_categories": undeclared,
        "declared_dead": declared,
    }

    if undeclared:
        named = ", ".join(
            f"{c} ({categories[c]['total']} features)" for c in undeclared
        )
        return CheckResult(
            name="Category Liveness",
            passed=False,
            message=f"{len(undeclared)} feature category(ies) wholly NaN: {named}",
            details=details,
        )

    suffix = f" ({len(declared)} declared-dead: {', '.join(declared)})" if declared else ""
    return CheckResult(
        name="Category Liveness",
        passed=True,
        message=f"All {len(categories) - len(declared)} live categories producing values{suffix}",
        details=details,
    )


def check_feature_ranges(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that key features are within expected ranges."""
    if df.empty:
        return CheckResult(
            name="Feature Ranges",
            passed=False,
            message="No data to check"
        )

    out_of_range = {}

    for feature, (min_val, max_val) in config.feature_ranges.items():
        if feature not in df.columns:
            continue

        values = df[feature].dropna()
        if len(values) == 0:
            continue

        below = (values < min_val).sum()
        above = (values > max_val).sum()

        if below > 0 or above > 0:
            out_of_range[feature] = {
                'below_min': int(below),
                'above_max': int(above),
                'actual_range': f"[{values.min():.4g}, {values.max():.4g}]",
                'expected': f"[{min_val}, {max_val}]"
            }

    if out_of_range:
        return CheckResult(
            name="Feature Ranges",
            passed=False,
            message=f"{len(out_of_range)} features outside expected range",
            details=out_of_range
        )

    return CheckResult(
        name="Feature Ranges",
        passed=True,
        message=f"All {len(config.feature_ranges)} monitored features within range"
    )


def check_cross_symbol_consistency(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that all symbols have similar row counts."""
    if df.empty:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=False,
            message="No data to check"
        )

    counts = df.groupby('symbol').size()

    if len(counts) < 2:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=True,
            message=f"Only {len(counts)} symbol(s), skipping comparison"
        )

    max_count = counts.max()
    min_count = counts.min()
    ratio_diff = (max_count - min_count) / max_count

    details = {sym: int(cnt) for sym, cnt in counts.items()}
    details['ratio_diff'] = f"{ratio_diff:.1%}"

    if ratio_diff > config.max_count_ratio_diff:
        return CheckResult(
            name="Cross-Symbol Consistency",
            passed=False,
            message=f"Row count varies by {ratio_diff:.1%} (threshold: {config.max_count_ratio_diff:.0%})",
            details=details
        )

    return CheckResult(
        name="Cross-Symbol Consistency",
        passed=True,
        message=f"Row counts consistent across symbols (diff: {ratio_diff:.1%})",
        details=details
    )


def check_data_rate(df: pd.DataFrame, config: ValidationConfig) -> CheckResult:
    """Check that data rate meets expectations."""
    if df.empty:
        return CheckResult(
            name="Data Rate",
            passed=False,
            message="No data to check"
        )

    ts_col = get_timestamp_col(df)

    # Calculate time span
    min_ts = df[ts_col].min()
    max_ts = df[ts_col].max()
    duration_hours = (max_ts - min_ts) / 1e9 / 3600

    if duration_hours < 0.1:
        return CheckResult(
            name="Data Rate",
            passed=True,
            message=f"Insufficient duration ({duration_hours:.2f}h) for rate check"
        )

    # Check rate per symbol
    rate_info = {}
    low_rate_symbols = []

    for symbol in df['symbol'].unique():
        sym_count = len(df[df['symbol'] == symbol])
        rate_per_hour = sym_count / duration_hours
        rate_info[symbol] = f"{rate_per_hour:.0f}/hour"

        if rate_per_hour < config.min_records_per_hour:
            low_rate_symbols.append(symbol)

    rate_info['duration_hours'] = f"{duration_hours:.2f}"

    if low_rate_symbols:
        return CheckResult(
            name="Data Rate",
            passed=False,
            message=f"{len(low_rate_symbols)} symbol(s) below {config.min_records_per_hour}/hour",
            details=rate_info
        )

    return CheckResult(
        name="Data Rate",
        passed=True,
        message=f"All symbols meet minimum rate ({config.min_records_per_hour}/hour)",
        details=rate_info
    )


def check_sequence_monotonicity(df: pd.DataFrame) -> CheckResult:
    """Check that sequence IDs are monotonically increasing per symbol."""
    if df.empty:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=False,
            message="No data to check"
        )

    # Check if sequence_id column exists
    if 'sequence_id' not in df.columns:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=True,
            message="No sequence_id column (older schema), skipping"
        )

    issues = {}

    for symbol in df['symbol'].unique():
        ts_col = get_timestamp_col(df)
        sym_df = df[df['symbol'] == symbol].sort_values(ts_col)
        seq_ids = sym_df['sequence_id'].dropna().values

        if len(seq_ids) < 2:
            continue

        # Check for non-increasing sequences
        diffs = np.diff(seq_ids)
        non_increasing = (diffs <= 0).sum()

        if non_increasing > 0:
            issues[symbol] = {
                'non_increasing_count': int(non_increasing),
                'first_seq': int(seq_ids[0]),
                'last_seq': int(seq_ids[-1])
            }

    if issues:
        return CheckResult(
            name="Sequence Monotonicity",
            passed=False,
            message=f"{len(issues)} symbol(s) have non-monotonic sequences",
            details=issues
        )

    return CheckResult(
        name="Sequence Monotonicity",
        passed=True,
        message="All sequences monotonically increasing"
    )


# =============================================================================
# Main Validation
# =============================================================================

def validate(data_dir: Path, config: ValidationConfig, hours: Optional[int] = None,
             quiet: bool = False) -> ValidationReport:
    """Run all validation checks. ``quiet`` suppresses progress prints (for --json)."""
    def _say(msg):
        if not quiet:
            print(msg)

    _say(f"\n  Scanning {data_dir}...")

    # Find files
    files = find_parquet_files(data_dir, hours)
    _say(f"  Found {len(files)} Parquet file(s)")

    if not files:
        return ValidationReport(
            data_dir=str(data_dir),
            timestamp=datetime.now(),
            total_files=0,
            total_rows=0,
            symbols=[],
            date_range=(None, None),
            checks=[CheckResult(
                name="Data Presence",
                passed=False,
                message="No Parquet files found"
            )]
        )

    # Load data
    _say("  Loading data...")
    df = load_data(files)
    _say(f"  Loaded {len(df):,} rows")

    # Extract metadata
    symbols = sorted(df['symbol'].unique().tolist()) if not df.empty else []

    if not df.empty:
        try:
            ts_col = get_timestamp_col(df)
            min_ts = pd.Timestamp(df[ts_col].min(), unit='ns')
            max_ts = pd.Timestamp(df[ts_col].max(), unit='ns')
            date_range = (min_ts.strftime('%Y-%m-%d %H:%M'), max_ts.strftime('%Y-%m-%d %H:%M'))
        except (ValueError, KeyError):
            date_range = (None, None)
    else:
        date_range = (None, None)

    # Run checks
    _say("  Running validation checks...")
    checks = [
        check_file_integrity(files),
        check_continuity(df, config),
        check_nan_ratio(df, config),
        check_category_liveness(df, config),
        check_feature_ranges(df, config),
        check_cross_symbol_consistency(df, config),
        check_data_rate(df, config),
        check_sequence_monotonicity(df),
    ]

    return ValidationReport(
        data_dir=str(data_dir),
        timestamp=datetime.now(),
        total_files=len(files),
        total_rows=len(df),
        symbols=symbols,
        date_range=date_range,
        checks=checks
    )


def main():
    parser = argparse.ArgumentParser(
        description="Validate ING feature data quality",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "data_dir",
        nargs="?",
        default="./data/features",
        help="Data directory OR a single .parquet file to validate "
             "(default: ./data/features)"
    )
    parser.add_argument(
        "--hours",
        type=int,
        help="Only validate data from last N hours (ignored for a single file)"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit the report as JSON (machine-readable)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed output"
    )
    parser.add_argument(
        "--max-gap",
        type=float,
        default=5.0,
        help="Max allowed gap in seconds (default: 5.0)"
    )
    parser.add_argument(
        "--max-nan",
        type=float,
        default=0.01,
        help="Max allowed NaN ratio (default: 0.01)"
    )

    args = parser.parse_args()

    # Setup config
    config = ValidationConfig(
        max_gap_seconds=args.max_gap,
        max_nan_ratio=args.max_nan
    )

    # Run validation
    target = Path(args.data_dir)
    if not target.exists():
        msg = f"Path does not exist: {target}"
        if args.json:
            print(_json.dumps({"verdict": "FAIL", "error": msg}))
        else:
            print(f"\n  Error: {msg}")
        sys.exit(1)

    single_file = target.is_file()
    if single_file and target.suffix != ".parquet":
        msg = f"Not a .parquet file: {target}"
        if args.json:
            print(_json.dumps({"verdict": "FAIL", "error": msg}))
        else:
            print(f"\n  Error: {msg}")
        sys.exit(1)

    report = validate(target, config, args.hours, quiet=args.json)

    if args.json:
        print(_json.dumps(report.to_dict(), indent=2, default=str))
    else:
        report.print_report(verbose=args.verbose)

    # Exit code: a single file exits nonzero only on a hard FAIL (WARN is ok);
    # directory mode keeps its historical strict behavior (any failing check → 1).
    if single_file:
        sys.exit(1 if report.verdict == "FAIL" else 0)
    sys.exit(0 if report.passed else 1)


if __name__ == "__main__":
    main()
