global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nat-ingestor'
    static_configs:
      - targets: ['nat-ingestor:9090']
        labels:
          service: 'ingestor'
